### ISSUE TITLE
entry ElapsedTicks

### ISSUE THREAD

**Issue by lobster2012-user** [Belorus/XLog#1]
Hello from Habra)

https://msdn.microsoft.com/ru-ru/library/system.diagnostics.stopwatch.elapsedticks(v=vs.110).aspx

Stopwatch ticks are different from DateTime.Ticks. Each tick in the DateTime.Ticks value represents one 100-nanosecond interval. Each tick in the ElapsedTicks value represents the time interval equal to 1 second divided by the Frequency.

**Comment by Belorus** [comment]
Thanks, fixed!

Quite silly mistake, that lead to 3x slowdown of logtime.
I reverted to approach that is a little bit slower, but still much faster than DateTime.Now

https://github.com/Belorus/XLog/commit/8a4720e0f264f3e7137d4abe58652354f03441dc

**Comment by lobster2012-user** [comment]
TimezoneOffsetTicks = (DateTime.UtcNow - DateTime.Now).Ticks;
TimeStamp = DateTime.UtcNow.AddTicks(TimezoneOffsetTicks);
1. Это будет работать неправильно. ( TimezoneOffsetTicks as t  => t = -t)
2. Можно оставить TimeStamp = DateTime.Now
   А зачем  использование  TimezoneOffsetTicks? . Это учтет онлайн изменение часового пояса что ли?
3. StopWatch.ElapsedTime(тут зависит от реализации, может не давать точность менее 1 мс(из-за округления), надо смотреть) или тоже самое winapi 
   QueryPerformanceFrequency
   QueryPerformanceCounter

В дизассемблере можно глянуть реализацию Stopwatch

**Comment by Belorus** [comment]
1. Поменял местами UtcNow и Now
2. Только из за производительности. DateTime.Now очень медленно работает.
3. Библиотека кроссплатформенная. Не везде есть WinApi. Не хотелось бы писать платформенные счетчики времени для Android/iOS. А точность дискретнее 1мс логгеру не нужна.

**Comment by lobster2012-user** [comment]
Всё понял, спасибо за разъяснения.
